# Introduction to Neural Networks in Pytorch

In [0]:
import torch
import numpy as np

In [0]:
def sigmoid(x):
  """
  Sigmoid activation function.

  Parameters:
    x: The torch.Tensor
  """
  return 1/(1+torch.exp(-x))

## Creating a Single Layer Neural Network
First we need to seed random data into our network.

In [0]:
 # Set seed so data is consistent 
torch.manual_seed(7)

 # Creates features with random 5 normal variables (samples from normal distribution)
features = torch.randn((1, 5)) # 1 row, 5 column tensor

# Creates a tensor with the same shape, but random values in the tensor
weights = torch.randn_like(features)

# Creates bias with random tensor
bias = torch.randn((1, 1)) # 1 row, 1 column - 1 value

In [14]:
print(weights)
print(features)
print(bias)

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[0.3177]])


# Useful Tensor Operations
**Multiplying Tensors**: `torch.mm(tensor1, tensor2)`
- Ensure that the shapes of the tensors can be multipled
- You can check this using `tensor.shape`

**Reshaping Tensors**: 
- `tensor.reshape(a, b)`: Returns new tensor with same data, but different dimensions
  - Sometimes returns data from memory (so no new copy of tensor is being formed)
  - Sometimes returns a clone (not from memory anymore) - Less efficient
- `tensor.resize_(a, b)`: Returns new tensor **inplace** (the `_` means inplace).
  - If you change the shape of a tensor, you risk cutting off data with this function.
- `tensor.view(a, b)`: Returns new tensor **inplace** AND returns an error if data from your tensor is going to be cut off after reshaping. 

### Calculating the output of the Single Neural Network
Before running this cell, both `weights.shape` and `features.shape` are (1x5). So we need to reshape `weights` as (5x1) to allow matrix multiplication. 

In [15]:
sigmoid(torch.mm(features, weights.view(5, 1)) + bias)

tensor([[0.1595]])

## Creating Neural Networks with a Hidden Layer (Matrix Multiplication)
Here is the network we are trying to implement
![](https://miro.medium.com/max/2544/1*AsyiK7G4X4i4lf3znvwoIQ.png)

In [0]:
torch.manual_seed(7)

# Creates 3 features
features = torch.randn((1, 3))

# Define the size (# of neurons) in each layer 
num_input = features.shape[1] # 3 input neurons (3 features)
num_hidden = 2
num_output = 1

# Create the weights between input and hidden layers (3 weights/neuron)
w1 = torch.randn(num_input, num_hidden) # 3x2 (helps to write it out on paper)
w2 = torch.randn(num_hidden, num_output) # 2x1

# Create bias
b1 = torch.randn(num_hidden) # 1x2 (2 values for 2 bias - 1 bias/neuron)
b2 = torch.randn(num_output)

### Calculating the output of the Multilayer Network
Following the diagram and writing this on paper can help with understanding.

In [17]:
layer1 = sigmoid(torch.mm(features, w1) + b1)
layer2 = sigmoid(torch.mm(layer1, w2) + b2)
layer2

tensor([[0.3171]])

## Numpy to Tensor and vice-versa
**Numpy -> Tensor**: `torch.from_numpy(a)`

**Tensor -> Numpy**: `tensor.numpy()`

**Note**: The memories are shared. So if you change the values in the tensor, it will be changed in the numpy array too.

In [18]:
torch.from_numpy(np.array([1, 2, 3, 4]))

tensor([1, 2, 3, 4])

In [19]:
layer2.numpy()

array([[0.31708315]], dtype=float32)